from __future__ import annotations

from typing import Any, Dict, Tuple


ShotTuple = Tuple[str, str, str]


PRODUCT_SHOT_RULE_PRIORITY: Tuple[str, ...] = (
    "wedding_pillowcase",
    "baby_pillowcase",
    "linen_pillowcase",
    "ring_bearer_pillow",
    "hoops_with_photos",
    "wedding_hoop",
    "bride_handkerchief",
    "vows_book",
    "guest_book",
    "bouquet_ribbon",
    "fabric_cross",
    "dress_baby",
    "plush",
)


PRODUCT_SHOT_RULES: Dict[str, Dict[str, Any]] = {
    "plush": {
        "display_name": "Gấu bông",
        "aliases": (
            "Gấu bông",
            "gau bong",
            "gaubong",
            "teddy bear",
            "stuffed bear",
            "stuffed toy",
            "plush toy",
            "plush",
        ),
        "lock": "the main product must remain the same soft plush/stuffed toy with the exact silhouette, fabric pile, seams, face/features, embroidered name or motif placement, proportions, and cuddly scale from the source image",
        "shots": (
            ("Product display", "Product display", "3 gấu bông tên thêu khác nhau trên bàn gỗ sồi sáng, vài đồ chơi trẻ em xung quanh, ánh sáng cửa sổ trái, nền kem blur nhẹ, bố cục 1:1"),
            ("Lifestyle", "Baby hug", "Tay bé nhỏ mặc romper len kem ôm gấu sát ngực, frame cắt ngang vai, không thấy mặt, cửa sổ sáng buổi sáng, tông soft"),
            ("Lifestyle", "Baby sleep", "Góc chụp cao xuống, bé ngủ say trên chăn linen kem ôm gấu bông, ánh sáng dreamy lọc qua rèm trắng, pastel tone"),
            ("Lifestyle", "Mẹ & bé trên sofa", "Mẹ bế bé ngồi trên sofa, bé trên lòng mẹ mặt quay ra ngoài ôm gấu, nursery sáng ấm, tông màu tự nhiên"),
            ("Lifestyle", "Nursery cot", "Gấu bông trong cũi gỗ trắng Scandinavian, chăn waffle kem, 2 gối thêu hoa dusty pink & sage, ánh sáng rèm trắng"),
            ("Gift box", "Gift box", "Gấu trong hộp kraft mở nắp, lót tissue, bố cục flat lay nền linen, trình bày quà tặng cao cấp nhưng không thêm chữ/nhãn đọc được"),
            ("Cận thêu tay", "Cận thêu tay", "Macro từng mũi thêu trên vải plush, ánh sáng side-light nổi texture vải, DOF nông, chỉ vùng thêu nét sắc"),
            ("Lifestyle", "Bé ôm trên chăn muslin", "Bé nằm trên chăn muslin hồng nhạt, 2 tay ôm gấu bông áp ngực, tay & ngực bé thấy rõ, ánh sáng tự nhiên buổi sáng"),
            ("Flat lay", "Flat lay baby shower", "Top-down: gấu trong rổ mây có lớp voile mỏng, kết hợp giày len mini, vòng gỗ teething, gối woolen nhỏ làm baby shower props"),
            ("Bối cảnh đặc biệt", "Vintage floral", "Gấu nằm trên chăn quilted hoa vintage dusty pink, floral nhỏ phong cách bà ngoại, bình đồng thau nhỏ, baby's breath và lavender, ánh sáng mềm"),
            ("Editorial/Grid", "Editorial quy trình", "Một ảnh editorial 1:1 dạng grid quy trình 3x2 hoặc 4x2, mỗi ô là một bước tạo ra gấu bông, viền kem mỏng, layout Pinterest mềm mại"),
        ),
    },
    "fabric_cross": {
        "display_name": "Fabric Cross",
        "aliases": (
            "Fabric Cross",
            "fabric cross",
            "soft cross",
            "linen cross",
            "baby cross",
            "cross keepsake",
            "thánh giá vải",
            "thanh gia vai",
        ),
        "lock": "the main product must remain the same soft fabric cross keepsake with the exact cross shape, stitched edge, fabric texture, embroidery/name placement, scale, and gentle baby keepsake identity from the source image",
        "shots": (
            ("Lifestyle", "Baby cầm 2 tay", "Bé 2 tay bế nhẹ fabric cross, nằm hoặc ngồi trong nursery/home ấm, ánh tự nhiên, bé và cross cùng nổi bật"),
            ("Product display", "Tựa gấu teddy + chăn len", "Cross dựng đứng tựa vào gấu teddy mềm trên chăn len kem, bên cạnh vài nhánh hoa hoặc lá khô nhỏ, nursery setting ấm"),
            ("Product display", "Treo mobile cũi gỗ", "Cross treo trên thanh mobile cũi gỗ tự nhiên trong nursery, phía dưới có cũi và chăn linen, ánh sáng cửa sổ"),
            ("Product display", "Trên tay nắm cửa gỗ", "Cross treo trên tay nắm cửa gỗ tròn trong phòng trẻ yên tĩnh và minimal, ánh sáng tự nhiên"),
            ("Product display", "2 cross trên chăn dệt", "2 fabric cross tên khác nhau xếp đều trên chăn dệt texture phong phú, styled elegant, nhẹ nhàng"),
            ("Lifestyle", "Candid bé cầm 1 tay", "Bé cầm cross 1 tay trong khi đang bò, ngồi hoặc vui chơi, khoảnh khắc candid tự nhiên, ánh sáng mềm"),
            ("Quy trình", "Quy trình 4 ảnh nhỏ", "Một ảnh 1:1 mosaic 2x2 ghi quy trình làm cross: cắt vải, thêu, hoàn thiện, sản phẩm cuối"),
            ("Product display", "Khung cảnh nursery", "Cross đặt trong khung cảnh nursery đẹp trên kệ hoặc bên đồ chơi, background blur nhẹ, product là focal point"),
            ("Cận thêu tay", "Cận thêu tay", "Macro chi tiết thêu trên fabric cross: từng mũi chỉ, màu sắc chỉ, texture vải nổi rõ"),
            ("Lifestyle", "Candid bé + cross #2", "Góc chụp candid thứ 2 của bé với cross, bối cảnh hoặc góc khác ảnh candid trước, ánh sáng tự nhiên"),
            ("Product display", "Product display đơn", "Cross trong bố cục display đơn, nền neutral sạch, ánh sáng đều, tối giản"),
            ("Product display", "Composite layout", "Một ảnh 1:1 trình bày 3-4 góc chụp của cùng 1 cross trong layout editorial sạch, cho thấy tổng quan product từ nhiều góc độ"),
            ("Editorial/Grid", "Editorial grid layout", "Grid layout editorial Pinterest ghép nhiều shot theo bố cục ô vuông sạch, vẫn giữ cross là sản phẩm chính"),
        ),
    },
    "bride_handkerchief": {
        "display_name": "Bride Handkerchief",
        "aliases": (
            "Bride Handkerchief",
            "bride handkerchief",
            "bridal handkerchief",
            "wedding handkerchief",
            "embroidered handkerchief",
            "khăn tay cô dâu",
            "khan tay co dau",
        ),
        "lock": "the main product must remain the same embroidered wedding handkerchief or soft cloth square with the exact fabric, edge finish, fold/open shape, motif placement, stitch colors, and elegant keepsake scale from the source image",
        "shots": (
            ("Lifestyle", "2 khăn 2 màu cạnh nhau", "2 khăn thêu cùng họa tiết nhưng 2 màu vải khác nhau đặt song song, phong cách lifestyle, thể hiện tùy chọn màu"),
            ("Product display", "Flat display đơn", "Khăn xếp vuông phẳng hoặc mở ra nhẹ, họa tiết thêu nổi bật trực tiếp, nền neutral sạch"),
            ("Gift box", "Gift box", "Khăn gấp gọn trong hộp quà sang trọng, ribbon, decor cưới nhẹ nhàng, không có chữ/nhãn đọc được"),
            ("Product display", "3 khăn 3 màu", "3 khăn cùng họa tiết, 3 màu vải khác nhau bày cạnh nhau, cho khách thấy full color options"),
            ("Product display", "Trên vải mềm + decor", "Khăn đặt trên vải mềm satin hoặc linen mịn, bên cạnh hoa nhỏ hoặc ribbon, ánh sáng tự nhiên"),
            ("Lifestyle", "Chú rể cầm khăn", "Chú rể cầm khăn thêu tay trong bối cảnh hôn lễ, ảnh thanh lịch, góc view chú rể"),
            ("Product display", "Tổng hợp nhiều góc", "Một ảnh 1:1 trình bày nhiều góc nhìn của cùng 1 khăn, editorial style, họa tiết thêu vẫn rõ"),
            ("Product display", "Flat display #3", "Flat display lần 3 với bố cục hoặc props khác như nến, nhẫn, hoa cưới nhỏ"),
        ),
    },
    "vows_book": {
        "display_name": "Vows Book",
        "aliases": (
            "Vows Book",
            "vow book",
            "vows book",
            "wedding vows",
            "bride vows",
            "groom vows",
            "sổ vows",
            "so vows",
        ),
        "lock": "the main product must remain the same fabric-covered vow book/booklet with the exact book cover shape, spine/edge construction, embroidered cover layout, lettering placement, fabric texture, and wedding keepsake identity from the source image",
        "shots": (
            ("Lifestyle", "Đôi uyên ương cùng đọc", "Cô dâu và chú rể ngồi cạnh nhau đọc vow books trong bối cảnh hôn lễ lãng mạn, intimate và tender"),
            ("Product display", "2 cuốn windowsill", "2 vow books trên bậu cửa sổ, ánh sáng tự nhiên bên, bố cục thanh lịch nhìn từ bên cạnh"),
            ("Flat lay", "Flat lay vow books + props", "2 vow books flat lay với props cưới như nhẫn, hoa khô, ribbon, không thêm text overlay"),
            ("Cận thêu tay", "Cận thêu tay", "Macro chi tiết thêu và texture vải bìa vow book, chỉ màu và từng mũi thêu rõ nét"),
            ("Gift box", "Gift box", "2 vow books trong hộp quà cưới mở, trình bày tặng phẩm wedding sang trọng"),
            ("Product display", "2 cuốn bìa rõ cả 2", "2 vow books đặt để nhìn rõ cả 2 bìa thêu Bride's Vows và Groom's Vows nếu nguồn có chữ đó, bố cục symmetrical"),
            ("Lifestyle", "Cầm tại bàn tiệc cưới", "Cầm vow book trong bối cảnh reception hoặc bàn tiệc cưới, ánh sáng mềm sang trọng"),
        ),
    },
    "ring_bearer_pillow": {
        "display_name": "Ring Bearer Pillow",
        "aliases": (
            "Ring Bearer Pillow",
            "ring bearer pillow",
            "wedding ring pillow",
            "ring pillow",
            "gối nhẫn",
            "goi nhan",
        ),
        "lock": "the main product must remain the same ring bearer pillow with the exact cushion shape, fabric surface, embroidery/floral motif placement, ribbon/ring attachment area if present, soft volume, seams, and wedding ceremony scale from the source image",
        "shots": (
            ("Product display", "Đứng trên gỗ sơn trắng", "Gối dựng đứng trên bề mặt gỗ sơn trắng, không gian nội thất elegant soft, trang trí floral nhẹ xung quanh"),
            ("Product display", "Kế hộp nhẫn gỗ mở", "Gối đặt cạnh hộp nhẫn gỗ đang mở có 2 nhẫn vàng, bàn nội thất serene, props cưới tối giản"),
            ("Product display", "3 chiếc trên kệ tường", "3 gối 3 kệ tường treo, gối giữa cao hơn một chút, bố cục elegant 3 tầng trong không gian nội thất"),
            ("Product display", "Trên vải satin trắng", "Gối đặt trên vải satin trắng mềm, bên cạnh hoa hồng và nến nhỏ, bối cảnh nội thất cưới elegant"),
            ("Product display", "Trên giá gỗ ngoài trời", "Gối dựng trên giá gỗ nhỏ rustic, bối cảnh outdoor wedding, ánh sáng tự nhiên garden"),
            ("Cận thêu tay", "Cận thêu hoa", "Close-up họa tiết thêu hoa trên gối, từng mũi chỉ và texture vải nổi rõ, DOF nông"),
            ("Gift box", "Gift box", "Gối trong hộp quà wedding sang trọng mở nắp, nội thất soft elegant, ribbon và lining trắng"),
            ("Lifestyle", "Cô dâu cầm nhẹ nhàng", "Cô dâu 2 tay cầm nhẹ gối trong không gian hôn lễ, bối cảnh tender và elegant, váy cưới hiện nhẹ"),
            ("Product display", "Trong xe ngựa gỗ miniature", "Gối đặt trong xe ngựa gỗ miniature trang trí nhỏ, không gian nội thất elegant sáng nhẹ"),
            ("Lifestyle", "Đôi uyên ương cùng cầm", "Cô dâu và chú rể ngồi cạnh nhau cùng cầm gối, bối cảnh indoor wedding elegant"),
            ("Lifestyle", "Cận đôi tay cầm gối", "Close-up đôi tay cô dâu và chú rể cùng nâng gối nhẹ nhàng, nhẫn cưới thấy rõ"),
            ("Quy trình", "Process tay thêu cận", "Cận cảnh tay đang thêu trên vải gối, kim và chỉ màu, bối cảnh thủ công ấm cúng"),
        ),
    },
    "guest_book": {
        "display_name": "Guest Book",
        "aliases": (
            "Guest Book",
            "guest book",
            "wedding guest book",
            "embroidered guest book",
            "sổ ký tên",
            "so ky ten",
            "sổ khách",
            "so khach",
        ),
        "lock": "the main product must remain the same fabric-covered wedding guest book with the exact book shape, cover material, embroidery placement, spine/edge construction, lettering/motif style, and elegant keepsake scale from the source image",
        "shots": (
            ("Product display", "Trên vải trắng + props cưới", "Guest book đặt trên vải trắng mềm, kề nhẫn cưới và hoa nhỏ, không gian elegant wedding"),
            ("Cận thêu tay", "Cận thêu tay", "Close-up họa tiết thêu tay trên bìa vải guest book, chi tiết mũi chỉ và màu sắc rõ nét"),
            ("Product display", "Dựng trên giá gỗ nhỏ", "Guest book dựng đứng trên giá nhỏ, bàn trắng sạch, bối cảnh wedding minimal sáng"),
            ("Lifestyle", "Cô dâu cầm gracefully", "Cô dâu nhẹ nhàng cầm hoặc giữ guest book, váy cưới, bối cảnh nội thất hoặc vườn wedding"),
            ("Lifestyle", "Đôi uyên ương ngồi ngoài trời", "Cô dâu và chú rể ngồi cạnh nhau trong vườn romantic, cùng xem guest book, ánh sáng ngoài trời"),
            ("Product display", "Trên bàn gỗ sáng + décor", "Guest book trên bàn gỗ light-toned, bố cục flat hoặc dựng nghiêng, props cưới nhẹ bên cạnh"),
            ("Lifestyle", "Đôi uyên ương đứng ngoài trời", "Cô dâu và chú rể đứng ngoài trong vườn wedding, softly cầm guest book, góc chụp khác ảnh ngồi"),
            ("Product display", "3 cuốn flat lay trên tulle", "3 guest books khác nhau bày flat trên nền tulle trắng, bố cục elegant, thể hiện bộ sưu tập"),
            ("Gift box", "Gift box", "Guest book trong hộp quà sang trọng mở nắp, trình bày quà tặng cưới, ribbon và lining"),
        ),
    },
    "bouquet_ribbon": {
        "display_name": "Bouquet Ribbon",
        "aliases": (
            "Bouquet Ribbon",
            "bouquet ribbon",
            "bridal bouquet ribbon",
            "wedding ribbon",
            "embroidered ribbon",
            "ribbon cưới",
            "ribbon cuoi",
            "dải ruy băng",
            "dai ruy bang",
        ),
        "lock": "the main product must remain the same long embroidered bouquet ribbon with the exact ribbon width, fabric drape, stitched lettering or motif placement, edge finish, color, and wedding accessory scale from the source image",
        "shots": (
            ("Lifestyle", "Ribbon trong bó hoa cưới", "Bó hoa cưới lộng lẫy tích hợp ribbon thêu, không có tay người, chỉ bó hoa và ribbon là focal"),
            ("Product display", "2 ribbon song song", "2 ribbon thêu tay đặt song song, 2 thiết kế hoặc màu khác nhau, showcasing options"),
            ("Product display", "Ribbon đơn dựng/cuộn", "1 ribbon cuộn hoặc xếp gọn trên bề mặt clean, trình bày product đơn thanh lịch"),
            ("Product display", "Ribbon quanh hoa cô dâu", "Bridal bouquet đẹp với ribbon thêu kết xung quanh cành hoa, làm nổi bật ribbon trên nền hoa"),
            ("Product display", "Bộ ribbon thêu", "Set nhiều ribbon thêu bày cùng nhau, showcasing đầy đủ collection trong 1 ảnh"),
            ("Product display", "Trang trí chai rượu cưới", "Ribbon buộc trang trí quanh cổ chai rượu vang cưới, wedding table decor vibe"),
            ("Product display", "Trong giỏ cưới", "Ribbon được xếp trong giỏ đan cưới đẹp kết hợp cùng các đồ trang trí wedding khác"),
            ("Lifestyle", "Cô dâu cầm ribbon", "Cô dâu cầm ribbon trong tay, bối cảnh hôn lễ, focus vào ribbon và đôi tay cô dâu"),
            ("Lifestyle", "Ribbon trên trang phục cô dâu", "Delicate ribbon gắn hoặc thắt trên phần váy/eo cô dâu, close-up hoặc mid-shot elegant"),
            ("Lifestyle", "Chú rể với ribbon #1", "Chú rể mang hoặc cài ribbon trong bối cảnh hôn lễ, góc chụp 1, showcase cách dùng phía chú rể"),
            ("Lifestyle", "Chú rể với ribbon #2", "Chú rể với ribbon, góc chụp hoặc bối cảnh khác so với ảnh chú rể #1"),
        ),
    },
    "wedding_hoop": {
        "display_name": "Wedding Hoop",
        "aliases": (
            "Wedding Hoop",
            "wedding hoop",
            "embroidery hoop wedding",
            "embroidered hoop",
            "hoop cưới",
            "hoop cuoi",
            "vòng thêu cưới",
            "vong theu cuoi",
        ),
        "lock": "the main product must remain the same circular embroidery hoop with the exact wooden hoop frame, stretched fabric, embroidered floral/name layout, stitch colors, hanging/display scale, and wedding keepsake identity from the source image",
        "shots": (
            ("Product display", "Flat display thêu hoa", "Vòng hoop nằm phẳng trên bề mặt sạch, họa tiết thêu hoa nổi bật trực tiếp, ánh sáng đều, nền neutral"),
            ("Cận thêu tay", "Cận thêu tay", "Macro họa tiết thêu hoa trên vải hoop: chỉ màu, từng mũi thêu, texture vải canvas nổi rõ"),
            ("Product display", "Giữa vest chú rể & áo cô dâu", "Hoop đặt giữa vest chú rể và phần váy cô dâu, styled như vật phẩm cưới quan trọng"),
            ("Lifestyle", "Cô dâu đứng cầm showcase", "Cô dâu đứng cầm vòng hoop, ánh sáng natural, bối cảnh hôn lễ, hoop là focal product"),
            ("Product display", "4 vòng trên voile trắng", "4 wedding hoops bày đẹp trên voile trắng mềm, trang trí hoa nhỏ elegant, showcasing collection"),
            ("Gift box", "Gift box", "Hoop trong hộp quà mở nắp, trình bày quà tặng cưới sang trọng, lót vải, ribbon"),
            ("Lifestyle", "Tay thêu process lifestyle", "Đôi bàn tay đang thêu hoop với kim và chỉ, process-lifestyle shot, ánh sáng ấm cúng thủ công"),
            ("Lifestyle", "Đôi uyên ương cầm #1", "Cô dâu và chú rể cùng cầm hoặc giữ hoop, bối cảnh hôn lễ indoor, góc chụp 1"),
            ("Product display", "2 vòng tên khác trên gỗ", "2 hoop cùng thiết kế khác tên đặt trên gỗ rustic, kết hợp props cổ điển, showcasing cá nhân hóa"),
            ("Product display", "Treo trên móc tường", "Hoop treo trên móc tường trong không gian reception hoặc nội thất nhà, wall decor vibe"),
            ("Product display", "Flat cận chi tiết thêu #2", "Flat display lần 2, cận hơn ảnh đầu, họa tiết thêu và texture vải embroidery rõ nét hơn"),
            ("Lifestyle", "Đôi uyên ương cầm #2", "Cô dâu và chú rể cầm hoop, góc hoặc bối cảnh khác so với ảnh cầm đầu tiên như ngoài trời hoặc mood khác"),
            ("Lifestyle", "Đôi từ phía sau outdoor", "Chụp từ phía sau đôi uyên ương ngoài trời, hoop thấy rõ trong tay, vườn cưới garden background"),
            ("Product display", "Kệ nhỏ ngoài trời reception", "Hoop trên kệ nhỏ trong không gian outdoor reception, ánh nắng tự nhiên, wedding table setting"),
        ),
    },
    "hoops_with_photos": {
        "display_name": "Hoops With Photos",
        "aliases": (
            "Hoops With Photos",
            "hoops with photos",
            "photo hoop",
            "baby photo hoop",
            "embroidery hoop photo",
            "khung thêu ảnh",
            "khung theu anh",
            "vòng thêu ảnh",
            "vong theu anh",
        ),
        "lock": "the main product must remain the same baby/nursery embroidery hoop or frame with photo/name/date elements exactly as in the source image, preserving hoop/frame shape, photo placement, stitched name/date layout, fabric texture, and keepsake wall decor scale",
        "shots": (
            ("Product display", "Kệ gỗ nursery 2 khung", "2 khung thêu tên khác nhau đặt trên kệ gỗ nursery, trang trí phòng bé, ánh sáng buổi sáng ấm"),
            ("Lifestyle", "Trong cũi gỗ buổi sáng", "Khung thêu ngồi trong cũi gỗ trắng, thú bông nhỏ bên cạnh, ánh sáng sáng ban mai lọc qua rèm"),
            ("Flat lay", "Flat lay chăn kem + decor bé", "Flat lay khung và đồ decor bé như thú nhỏ, hoa khô, ribbon nhỏ trên chăn kem mềm mịn"),
            ("Product display", "Treo tường nursery", "Khung treo tường trong nursery tông trung tính beige/white/sage, styled như wall art décor"),
            ("Lifestyle", "Mẹ cầm khung linen dress", "Phụ nữ mặc váy linen trắng hoặc be cầm nhẹ khung trong tay, ánh sáng tự nhiên, intimate và warm"),
            ("Cận thêu tay", "Macro thêu tên + ngày", "Close-up họa tiết thêu tên và ngày tháng trên khung, từng mũi chỉ rõ nét, DOF nông"),
            ("Product display", "Trên giỏ mây + decor bé", "Khung đặt trên hoặc trong giỏ mây, bên trong giỏ có đồ decor bé như giày nhỏ, hoa, ribbon"),
            ("Gift box", "Gift box quà tặng bé", "Khung trong hộp quà mở nắp, lót vải mềm, ribbon, bối cảnh baby gift đẹp và heartfelt"),
            ("Quy trình", "Process tay thêu", "Đôi tay đang thêu tên và ngày tháng lên khung, kim và chỉ, ánh sáng ấm cúng artisan"),
            ("Product display", "3 khung grouped tên khác", "3 khung thêu 3 tên khác nhau bày cùng nhau như bộ, showcasing personalization options"),
            ("Lifestyle", "Bé chạm tay vào khung", "Bé nhỏ tự cầm hoặc chạm tay vào khung thêu tên mình, khoảnh khắc dễ thương tự nhiên"),
            ("Lifestyle", "Mẹ bế bé bé ôm khung", "Mẹ bế bé trên tay, bé ôm hoặc nhìn vào khung thêu, lifestyle ấm áp tình cảm gia đình"),
            ("Product display", "Kệ bàn tiệc sinh nhật bé", "Khung đứng trên kệ nhỏ đặt trên bàn tiệc sinh nhật, birthday party decor xung quanh"),
        ),
    },
    "dress_baby": {
        "display_name": "Dress Baby",
        "aliases": (
            "Dress Baby",
            "baby dress",
            "toddler dress",
            "kids dress",
            "children dress",
            "embroidered dress",
            "váy bé",
            "vay be",
            "váy em bé",
            "vay em be",
        ),
        "lock": "the main product must remain the same baby/child dress with the exact dress silhouette, sleeves/ruffles/ties/hem, fabric color, embroidery placement, garment scale, and construction from the source image",
        "shots": (
            ("Product display", "4 váy 4 mannequin xếp hàng", "4 váy 4 màu khác nhau trên 4 mannequin trẻ em xếp hàng ngang, showcasing full color palette"),
            ("Product display", "3 váy bàn trắng side-by-side", "3 váy 3 màu đặt trên bàn trắng song song, cùng họa tiết thêu, thể hiện options màu sắc"),
            ("Product display", "2 váy flat lay 2 màu", "2 váy 2 màu trải phẳng cạnh nhau trên nền neutral, cùng họa tiết thêu, clean và clear"),
            ("Product display", "Mannequin 2 mặt trước/sau", "Váy trên mannequin trẻ em, 1 mặt trước và 1 mặt sau trong cùng 1 ảnh double shot, thể hiện toàn diện thiết kế"),
            ("Gift box", "Gift box quà sinh nhật", "Váy gấp gọn trong hộp giấy quà mở nắp, bối cảnh sáng airy, trình bày quà tặng bé"),
            ("Product display", "2 váy hanging 2 màu", "2 váy 2 màu treo trên móc/hanger cạnh nhau, dựng thẳng, showcasing màu sắc từ góc treo"),
            ("Lifestyle", "Bé mặc váy ngoài công viên", "Bé ngồi chơi hoặc picnic ngoài trời trên thảm cỏ, mặc váy thêu, ánh sáng tự nhiên garden ấm"),
            ("Lifestyle", "Bé mặc váy ngồi trên sofa", "Bé ngồi trên sofa tông neutral, đang chơi hoặc ăn trái cây, mặc váy thêu, tự nhiên cozy"),
            ("Lifestyle", "1-2 bé nền trắng", "1 bé nhìn thẳng và 1 bé nhìn sau, hoặc 2 bé mặc váy 2 màu trên nền trắng sạch"),
            ("Cận thêu tay", "Cận thêu ngực/tà váy", "Close-up họa tiết thêu trên phần ngực hoặc tà váy: chỉ màu, từng mũi, texture vải linen"),
            ("Quy trình", "Process mosaic may thêu", "Một ảnh mosaic quy trình may và thêu váy trẻ em: từ vải thô, thêu, may hoàn thiện, thành phẩm"),
        ),
    },
    "linen_pillowcase": {
        "display_name": "Linen Pillowcase",
        "aliases": (
            "Linen Pillowcase",
            "linen pillowcase",
            "linen pillow",
            "embroidered linen pillow",
            "vỏ gối linen",
            "vo goi linen",
            "gối linen",
            "goi linen",
        ),
        "lock": "the main product must remain the same linen pillowcase/cushion with the exact rectangular pillow shape, soft volume, linen weave, embroidered name or motif placement, seam/edge finish, fabric color, and home decor scale from the source image",
        "shots": (
            ("Lifestyle", "Phụ nữ cầm/ôm gối", "Phụ nữ đứng hoặc ngồi cầm/ôm gối linen tự nhiên, không gian phòng ngủ hoặc sofa, ánh sáng tự nhiên ấm"),
            ("Product display", "Hero 1 gối trên giường", "1 gối trên ga trải giường linen sạch, bối cảnh phòng ngủ minimal neutral, hero shot rõ ràng"),
            ("Product display", "2 gối cạnh nhau", "2 gối đặt cạnh nhau trên giường hoặc bề mặt, thể hiện 2 tùy chọn tên/màu"),
            ("Product display", "4 gối stack dọc", "4 gối xếp chồng lên nhau theo chiều dọc, 4 màu hoặc 4 tên, showcasing collection đầy đủ"),
            ("Product display", "3 gối 3 màu", "3 gối 3 màu vải khác nhau, cùng họa tiết thêu, bày side-by-side hoặc fan out nhẹ"),
            ("Cận thêu tay", "Cận thêu collage", "Một ảnh collage macro ghép nhiều góc cận thêu: từng mũi chỉ, texture vải linen, chữ thêu rõ nét"),
            ("Product display", "Bé nằm trên gối", "Bé nhỏ nằm ngủ hoặc chơi trên gối thêu tên, gối là hero product, nursery ấm nhẹ"),
            ("Product display", "Gối trên bàn/bề mặt + props", "Gối đặt trên bàn hoặc bề mặt, styled với props nhẹ nhàng như hoa, nến tealight, lá khô"),
            ("Quy trình", "Quy trình thêu", "Phụ nữ ngồi thêu tay trên vỏ gối, cận tay cầm kim và chỉ, không gian sáng thủ công ấm cúng"),
            ("Product display", "Standalone đơn #2", "Product display đơn lần 2, góc chụp hoặc bối cảnh khác so với hero trên giường"),
            ("Product display", "2 gối variant #2", "2 gối cạnh nhau, variant thứ 2, màu/bố cục/bối cảnh khác so với ảnh 2 gối đầu tiên"),
            ("Gift box", "Gift box", "Gối gấp gọn trong hộp giấy mở, họa tiết thêu thấy rõ, ribbon, trình bày quà tặng"),
        ),
    },
    "wedding_pillowcase": {
        "display_name": "Wedding Pillowcase",
        "aliases": (
            "Wedding Pillowcase",
            "wedding pillowcase",
            "wedding pillow",
            "bride groom pillow",
            "bride and groom pillow",
            "gối cưới",
            "goi cuoi",
            "vỏ gối cưới",
            "vo goi cuoi",
        ),
        "lock": "the main product must remain the same wedding pillowcase/cushion with the exact pillow shape, fabric surface, embroidered wedding lettering or motif placement, soft volume, seam/edge finish, and romantic keepsake scale from the source image",
        "shots": (
            ("Lifestyle", "Cô dâu ôm/cầm gối", "Cô dâu ôm hoặc cầm gối thoải mái, bối cảnh phòng ngủ hoặc chuẩn bị cưới, ánh sáng tự nhiên"),
            ("Product display", "Hero gối trên giường", "Gối trên giường linen wedding-toned, bối cảnh phòng ngủ cưới lãng mạn, hero shot chính"),
            ("Product display", "2 gối Bride & Groom", "2 gối Bride's và Groom's cạnh nhau nếu nguồn có chữ đó, cặp đôi tên thêu, showcasing wedding pair"),
            ("Product display", "4 gối stack dọc", "4 gối xếp chồng, 4 màu hoặc 4 tên khác, showcasing wedding pillow collection"),
            ("Product display", "3 gối 3 màu", "3 gối 3 màu vải cùng họa tiết thêu, side-by-side, thể hiện color options"),
            ("Cận thêu tay", "Cận thêu collage", "Một ảnh collage macro cận họa tiết thêu từ nhiều góc, texture vải linen wedding chất lượng cao"),
            ("Product display", "Standalone đơn", "1 gối product display đơn, bối cảnh wedding-neutral sạch"),
            ("Lifestyle", "Đôi uyên ương trên giường", "Cô dâu và chú rể nằm thoải mái trên giường, đầu gối gối thêu tên, ảnh romantic intimate"),
            ("Product display", "3 gối tổng hợp", "3 gối bày thành bộ, showcasing nhiều tùy chọn trong 1 ảnh duy nhất"),
            ("Quy trình", "Quy trình thêu", "Phụ nữ ngồi thêu tay trên vỏ gối, không gian sáng ấm, cận tay và sản phẩm đang thêu"),
            ("Product display", "Standalone #2", "Display đơn lần 2, góc hoặc props nhẹ khác"),
            ("Product display", "2 bé nằm trên 2 gối", "2 bé nhỏ nằm trên 2 gối tên khác nhau, lifestyle nhẹ nhàng, cute và shareable"),
            ("Product display", "2 gối realistic", "2 gối trình bày realistic/photographic chuyên nghiệp, bố cục sạch sẽ cho catalog"),
            ("Gift box", "Gift box quà cưới", "Gối đặt trong hộp giấy mở, họa tiết thêu nổi, ribbon, trình bày quà tặng cưới sang trọng"),
        ),
    },
    "baby_pillowcase": {
        "display_name": "Baby Pillowcase",
        "aliases": (
            "Baby Pillowcase",
            "baby pillowcase",
            "baby pillow",
            "nursery pillow",
            "children pillow",
            "gối em bé",
            "goi em be",
            "vỏ gối bé",
            "vo goi be",
            "gối bé",
            "goi be",
        ),
        "lock": "the main product must remain the same baby/nursery pillowcase or cushion with the exact pillow shape, soft volume, fabric weave, embroidered name/motif placement, seam/edge finish, color, and baby-safe nursery scale from the source image",
        "shots": (
            ("Lifestyle", "Mẹ bế bé + gối thêu tên", "Mẹ bế bé hoặc ngồi cùng bé, bé tiếp xúc hoặc nhìn gối thêu tên mình, ấm áp và tình cảm"),
            ("Product display", "Hero gối trên giường nursery", "Gối bé trên giường nursery, bối cảnh phòng bé tông nhạt trung tính, hero shot sạch"),
            ("Product display", "2 gối cùng màu khác tên", "2 gối cùng màu vải nhưng tên thêu khác nhau, thể hiện rõ personalization option"),
            ("Product display", "4 gối stack dọc", "4 gối xếp chồng, 4 tên hoặc màu khác, showcasing collection đầy đủ"),
            ("Product display", "3 gối 3 màu", "3 gối 3 màu vải, cùng họa tiết thêu tên, side-by-side thể hiện color variants"),
            ("Cận thêu tay", "Cận thêu collage", "Một ảnh collage macro: close-up họa tiết thêu tên, chữ thêu, hoa thêu nếu có, texture vải linen bé"),
            ("Product display", "Bé nằm trên gối", "Bé nằm ngủ hoặc tỉnh chơi thoải mái trên gối thêu tên, bối cảnh nursery ấm áp"),
            ("Product display", "3 gối tổng hợp", "3 gối trong bộ, bố cục đẹp, showcasing multiple name/color options"),
            ("Quy trình", "Quy trình thêu", "Phụ nữ ngồi thêu tên lên gối bé, cận tay thêu kim và chỉ, không gian ấm cúng thủ công"),
            ("Product display", "Standalone đơn", "Product display đơn 1 gối sạch sẽ, nền neutral tối giản"),
            ("Product display", "2 trẻ nằm 2 tên khác", "2 trẻ nhỏ nằm trên 2 gối tên khác nhau, lifestyle nhẹ nhàng tự nhiên"),
            ("Gift box", "Gift box quà sinh nhật", "Gối gói trong hộp giấy, họa tiết thêu nổi bật, trình bày quà tặng sinh nhật bé heartfelt"),
        ),
    },
}
